In [2]:
import numpy as np

In [3]:
one=np.ones([1,10,10])

In [4]:
one

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [5]:
n=1
for x in range(0,5):
    for y in range(0,10):
        one[0,x,y] = one[0,x,y]=n
        n+=1
n=1
for x in range(9,4,-1):
    for y in range(9,-1,-1):
        one[0,x,y] = one[0,x,y]=n
        n+=1
        

In [6]:
print(one)

[[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
  [31. 32. 33. 34. 35. 36. 37. 38. 39. 40.]
  [41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
  [50. 49. 48. 47. 46. 45. 44. 43. 42. 41.]
  [40. 39. 38. 37. 36. 35. 34. 33. 32. 31.]
  [30. 29. 28. 27. 26. 25. 24. 23. 22. 21.]
  [20. 19. 18. 17. 16. 15. 14. 13. 12. 11.]
  [10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]]]
